web:
  build: .
  #command: python3 ./pushpin-app/manage.py runserver 0.0.0.0:8000
  #command: /usr/local/bin/uwsgi --ini /root/pushpin-app/config/wsgi_config.ini
  command: /root/pushpin-app/config/web-run.sh
  volumes:
    - ./config/:/root/pushpin-app/config/:ro
    - ./pushpin-app/:/root/pushpin-app/
    - ./logs:/root/pushpin-app/logs/
  expose:
    - "8000"
  links:
    - postgres
    - rabbitmq:rabbit
  environment:
    POSTGRES_PASSWORD: 'mysecretpassword'
    POSTGRES_PORT: 5432
    PUSHPIN_PASSWORD: 'test'
    # change this to change the password for pushpin
    # either way, the username is 'test' (for now)
    SECRET_KEY: 'asdfjkl;1234567890qwertyuiop'
    # CHANGE THIS TO SOMETHING SECURE WHEN YOU DEPLOY
    DEBUG: True
    # Change to True for stack traces when errors occur
    ALLOWED_HOSTS: 'localhost'
    STATIC_URL: '/'

postgres:
  image: postgres
  environment:
    POSTGRES_PASSWORD: 'mysecretpassword'
    POSTGRES_USER: 'pushpin'

nginx:
  image: nginx
  volumes:
    - ./static/:/root/static/:ro
    - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./logs:/root/logs/
    # whatever directory is before the colon is where logs will go
  ports:
    - "8080:80"
    # whatever port you put before the colon will be where pushpin-web is served
  links:
    - web

rabbitmq:
  image: rabbitmq
  #environment:
    #RABBITMQ_NODENAME: rabbitmq-server

celery:
  #image: celery
  build: .
  command: /root/pushpin-app/config/celery-run.sh
  volumes:
    - ./config/:/root/pushpin-app/config/:ro
    - ./pushpin-app/:/root/pushpin-app/:ro
      #- ./logs:/root/pushpin-app/logs/
  links:
    - rabbitmq:rabbit
    - postgres
  environment:
    POSTGRES_PASSWORD: 'mysecretpassword'
    POSTGRES_PORT: 5432
